SOURCES 	  = main.c intr_vector_table.c
EXTRA_SOURCES = usercode/user_code.c usercode/user_entry.c 
RISC_V_TE 	  = /home/davide/RISC-V-TE
ARCH 		  = esp32c3
PORT 		  = /dev/ttyUSB0

include $(RISC_V_TE)/$(ARCH)/build.mk
